const Welcome = {
    "id": "Welcome",
    "name": "Welcome",
    "content": [
        { "text": "Welcome to BlueBook", "tabs": { "full": 0 }, "decos": ["middle", "Bold", "accent", "capital", "underline", "h1"] },
        { "text": "Your fast, minimal, keyboard-first note system.", "tabs": { "full": 0 }, "decos": ["middle", "bold", "accent", "small", "h2"] },
        { "tabs": { "full": 0 } },
        { "text": "This document is always here when you log in – your built-in help page and reference sheet.", "tabs": { "full": 0 } },
        { "tabs": { "full": 0 } },
        { "text": "Why This Editor Is Different", "tabs": { "full": 0 }, "decos": ["underline", "bold", "accent", "h3"] },
        { "text": "• No Markdown: what you type is what you get. No invisible syntax, no jumping cursors, no surprises.", "tabs": { "full": 0 } },
        { "text": "• Keyboard-first: every action has a hotkey. The mouse is completely optional.", "tabs": { "full": 0 } },
        { "text": "• Vim Mode: turn it on/off anytime.", "tabs": { "full": 0 } },
        { "text": "• Line Decorations: Bold, Underline, H1, H2, Accent… all done with hotkeys, not punctuation.", "tabs": { "full": 0 } },
        { "tabs": { "full": 0 } },
        { "text": "Try selecting this line and applying Bold or H2 using your hotkeys.", "tabs": { "full": 0 } },
        { "tabs": { "full": 0 } },
        { "text": "Math Support (MathJax)", "tabs": { "full": 0 }, "decos": ["underline", "bold", "accent", "h3"] },
        { "text": "Inline math looks like this: E^2=m^2c^4-p^2c^2.", "tabs": { "full": 0 }, "marks": [{ "role": "math", "from": 622, "to": 639 }] },
        { "tabs": { "full": 0 } },
        { "text": "Display math looks like this:", "tabs": { "full": 0 } },
        { "text": "i\\gamma^{\\mu}\\partial_{\\mu}\\psi-\\left(\\frac{mc}{\\hbar}\\right)\\psi=0", "tabs": { "full": 0 }, "decos": ["math"] },
        { "text": "Snippets make typing LaTeX fast: try typing \"tayl\" → expands to… well, whatever you configure it to.", "tabs": { "full": 0 } },
        { "tabs": { "full": 0 } },
        { "text": "Math snippets also work outside math – e.g. expanding \";i\" to \"=\".", "tabs": { "full": 0 } },
        { "tabs": { "full": 0 } },
        { "text": "Command Palette & File Picker", "tabs": { "full": 0 }, "decos": ["underline", "bold", "accent", "h3"] },
        { "text": "Open the command palette: <Meta+p>", "tabs": { "full": 0 } },
        { "text": "Type anything — it fuzzy-finds commands instantly.", "tabs": { "full": 0 } },
        { "tabs": { "full": 0 } },
        { "text": "Open the file picker: <Meta+o>", "tabs": { "full": 0 } },
        { "text": "• Fuzzy-find notes", "tabs": { "full": 0 } },
        { "text": "• Or create a new note by typing a name and pressing <Meta+Enter>", "tabs": { "full": 0 } },
        { "tabs": { "full": 0 } },
        { "text": "Try creating a note called “First thoughts”.", "tabs": { "full": 0 } },
        { "tabs": { "full": 0 } },
        { "text": "Snippets", "tabs": { "full": 0 }, "decos": ["underline", "bold", "accent", "h3"] },
        { "text": "Snippets expand both in normal text and inside LaTeX.", "tabs": { "full": 0 } },
        { "text": "You can customize or add your own in:", "tabs": { "full": 0 } },
        { "text": "• .config/snippets", "tabs": { "full": 0 } },
        { "text": "• See defaults in: .default/snippets", "tabs": { "full": 0 } },
        { "tabs": { "full": 0 } },
        { "text": "Here’s an example snippet demonstration:", "tabs": { "full": 0 } },
        { "text": "• Typing ;j → expands to \"(|)|\"", "tabs": { "full": 0 } },
        { "text": "• Typing inside inline math \"ee\" → expands to \"e^{|}|\"", "tabs": { "full": 0 } },
        { "tabs": { "full": 0 } },
        { "text": "Tabstops are predefined jump locations for your cursor in snippets. Move to the next tabstops with <Tab>.", "tabs": { "full": 0 } },
        { "tabs": { "full": 0 } },
        { "text": "Personal Configuration", "tabs": { "full": 0 }, "decos": ["underline", "bold", "accent", "h3"] },
        { "text": "All user-configurable files are just normal notes stored in:", "tabs": { "full": 0 } },
        { "text": "• .config/ — Your personal config", "tabs": { "full": 0 } },
        { "text": "• .default/ — The app’s shipped defaults", "tabs": { "full": 0 } },
        { "tabs": { "full": 0 } },
        { "text": "Open them like any other file. The editor doesn’t treat them specially — no magic, no formats to learn.", "tabs": { "full": 0 } },
        { "tabs": { "full": 0 } },
        { "text": "Common config files:", "tabs": { "full": 0 } },
        { "text": "• .config/hotkeys — your hotkeys", "tabs": { "full": 0 } },
        { "text": "• .config/theme — theme & colors", "tabs": { "full": 0 } },
        { "text": "• .config/snippets — snippets", "tabs": { "full": 0 } },
        { "text": "• .config/settings — general settings", "tabs": { "full": 0 } },
        { "tabs": { "full": 0 } },
        { "text": "You can edit them freely.", "tabs": { "full": 0 } },
        { "text": "If you break something, open the corresponding file in .default and copy it back.", "tabs": { "full": 0 } },
        { "tabs": { "full": 0 } },
        { "text": "Useful Hotkeys and Snippets", "tabs": { "full": 0 }, "decos": ["underline", "bold", "accent", "h3"] },
        { "text": "Replace these with your actual bindings:", "tabs": { "full": 0 } },
        { "text": "• Search notes: <Meta+o>", "tabs": { "full": 0 } },
        { "text": "• Command palette: <Meta+p>", "tabs": { "full": 0 } },
        { "text": "• Save file: <Meta+s>", "tabs": { "full": 0 } },
        { "text": "• Toggle Bold: <Meta+B>", "tabs": { "full": 0 } },
        { "text": "• Heading 1: <Meta+Shift+a> or h1", "tabs": { "full": 0 } },
        { "text": "• Heading 2: <Meta+Shift+s> or h2", "tabs": { "full": 0 } },
        { "text": "• Heading 3: <Meta+Shift+d> or h3", "tabs": { "full": 0 } },
        { "text": "• Heading 4: <Meta+Shift+f> or h4", "tabs": { "full": 0 } },
        { "text": "• No line decos: h0", "tabs": { "full": 0 } },
        { "text": "• Toggle display math: <Meta+d>", "tabs": { "full": 0 } },
        { "text": "• Toggle inline math: <Meta+i>", "tabs": { "full": 0 } },
        { "text": "• New note: <Meta+Enter> in the File Picker", "tabs": { "full": 0 } },
        { "tabs": { "full": 0 } },
        { "text": "Quick Demo Area", "tabs": { "full": 0 }, "decos": ["underline", "bold", "accent", "h3"] },
        { "text": "Try things out here:", "tabs": { "full": 0 } },
        { "text": "• Make this line bold", "tabs": { "full": 0 } },
        { "text": "• Make this a heading", "tabs": { "full": 0 } },
        { "text": "• Add some inline math: add the Pyhtagorean theorem here", "tabs": { "full": 0 } },
        { "text": "• Add display math to the next line: type in Maxwell's equations", "tabs": { "full": 0 } },
        { "tabs": { "full": 0 } },
        { "text": "• Trigger a snippet: writing paratheses is faster with ;j", "tabs": { "full": 0 } },
        { "text": "• Open the file picker and create a file named \"welcome_test\"", "tabs": { "full": 0 } },
        { "tabs": { "full": 0 } },
        { "text": "Have Fun", "tabs": { "full": 0 }, "decos": ["underline", "bold", "accent", "h3"] },
        { "text": "This app is built to be fast, predictable, and delightful with the keyboard.", "tabs": { "full": 0 } },
        { "text": "Customize everything. Experiment. Break things, fix them. Make it yours", "tabs": { "full": 0 } }
    ]
};

export default Welcome;
